### PR TITLE
Player stats

### PR DESCRIPTION
**Pull request by Ranran-the-JuicyPork**
https://forum.simutrans.com/index.php/topic,20548.0.html

### CODE REVIEW

**Comment by jamespetts** [comment]
This looks good and I have added the missing translation texts on my player-stats branch (have I missed any)? I note that I cannot see a post about this in the forum. May I ask whether you consider this ready for merging yet?

Thank you.

**Comment by Ranran-the-JuicyPork** [comment]
> I note that I cannot see a post about this in the forum.
https://forum.simutrans.com/index.php/topic,20548.0.html

> (have I missed any)?
```
player_stats
会社情報
Signalboxes
信号扱所
way_distances
総延長
Electrified Distances
電化総延長
Active lines
稼働路線数
Signals/signs
信号／標識
Vehicles
車両
Total
合計
Monthly maintenance cost details
月間維持管理費用
Number of depots per way type, and those monthly maintenance costs.
乗り物タイプごとの車庫数と月管理費用
hlptxt_mf_stations
乗り物タイプごとの対応駅数と合計月管理費用
Number of signalboxes and total monthly maintenance costs.
所有信号扱所の総数と月管理費用
hlptxt_mf_way_distances
所有道路、滑走路、軌道、水路の総延長と月管理費用
hlptxt_mf_electrified_distances
電化総延長と月管理費用
Number of signals and signs per way type, and those monthly maintenance costs.
信号、標識の総数と月管理費用
Number of active lines per way type.
乗り物タイプごとの稼働中の路線数
Number of convoys per way type, and inactive convoys number in parentheses.
乗り物タイプごとの編成数。カッコ内は車庫に留置中の編成数
Number of vehicles per way type, and those monthly maintenance costs.
`乗り物タイプごとの車両数と月あたり車両保存費
```
These are the additional terms for the Japanese version. Some terms may not need to be translated in English.

**Comment by jamespetts** [comment]
Thank you for that - I missed the post in the forum because it was in future feature discussions rather than patches/pull requests. I have now moved it accordingly. 

Subject to the translation issues, do you consider this ready for incorporation?

**Comment by Ranran-the-JuicyPork** [comment]
> Subject to the translation issues, do you consider this ready for incorporation?
Yes, after that, I hope that many people will use it in nightly builds and get feedback.

**Pull request merged**
