### PR TITLE
Enum cleanup for signalling, reservations, & goods GUI sort modes

### PR DESCRIPTION
**Pull request by freddyhayward**

### CODE REVIEW

**Comment by jamespetts** [comment]
Thank you for this - may I ask what the intention of this commit is?

**Comment by freddyhayward** [comment]
The intention was to make the code easier to maintain. It might be worthwhile for me to close this branch in favour of several smaller ones so that the purpose of each is clearer.

**Comment by jamespetts** [comment]
That would be helpful - thank you.

**Comment by freddyhayward** [comment]
I have made replacements with #239, #240, and #241.

**Pull request closed without merging**
