### PR TITLE
Std r10996

### PR DESCRIPTION
**Pull request by Ranran-the-JuicyPork**

### CODE REVIEW

**Comment by jamespetts** [comment]
Hello - in case you have not seen the message at the forum: I have tested the latest commit (dated 29 May 2024), but, unfortunately, this does not solve the problem described on the forum relating to querying the state of network servers: the original behaviour persists.

Additionally, there is now a problem relating to scrolling in the load and save game windows, where moving the mouse pointer up and down over the windows will scroll the list, whereas the mouse wheel does not work. This causes it to be nearly impossible to select a file name with the mouse. I suspect that this is related to code intended to make Simutrans workable for touch screens. 

Thank you for your work on this so far.

**Comment by Ranran-the-JuicyPork** [comment]
I think the mouse operation issue has been fixed.
Next, regarding networking, I have merged the commits related to the server frame, so please check if that makes any changes.

**Comment by jamespetts** [comment]
Thank you. I can confirm that the mouse interaction issue is fixed, but unfortunately the querying of a network game still fails with the error, "send of NWC_GAMEINFO failed" error message in the "Play online" window when I click on my local server in the list. This behaviour does not occur with the latest commit on the master branch.

**Comment by Ranran-the-JuicyPork** [comment]
I would like to have you split off and test the std-r10996 branch to understand or work around the issues and move forward.
Please test the std2406-1 branch in pull request #662 instead.

It will skip some commits, but will pick up many commits because it fixes a scrolling bug.

I forgot to report this before, but as an appearance change, striped lists will be introduced to some lists.
However, the goods list will not be changed because it works differently. The same applies to standard.

**Pull request closed without merging**
